### ISSUE TITLE
Finish employment editor mockups

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/orcid-app#10]
Finish mockups and get sign off on both mockups and business process behind then.

**Comment by jrmerz** [comment]
from @wrenaria 

![addemployment3-100-6](https://user-images.githubusercontent.com/1852393/47236954-7667cc00-d392-11e8-89b2-7ab4a9151f3d.jpg)

**Comment by jrmerz** [comment]
from @Vensberg "Note on the pre-selection logic: pre-select only ODR entry if complete. If not, pre-select PPS entries. Organizations are good."

**Comment by jrmerz** [comment]
@Vensberg @qjhart if we have sign off here I will close issue and get to work on implementation.

**Comment by qjhart** [comment]
@Vensberg, leaving sign-off to you

**Comment by jrmerz** [comment]
@Vensberg I think we had sign off on this, please reopen if not.
