### ISSUE TITLE
User testing

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/orcid-app#19]
@qjhart started some fake accounts, would be nice to be able to fully test those accounts by mock linking them to real UCD IAM data.

@jrmerz can create mock process for dev.

**Comment by qjhart** [comment]
There are currently 3 fake accounts;

| orcid | email | pw | 
| --- | --- | --- |
https://sandbox.orcid.org/0000-0001-9483-2817 | qjhart+bm@mailinator.com | quinnisgreat#1
https://sandbox.orcid.org/0000-0002-4111-8369  | qjhart+sl@mailinator.com | quinnisgreat#1
https://sandbox.orcid.org/0000-0003-2650-7566 | qjhart+gen@mailinator.com | quinnisgreat#1

You can update passwords for those if you want, by sending a PW change request and then using mailinator.com at those email accounts.
