### ISSUE TITLE
Finish Help Text for Checklist

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/orcid-app#21]
We need designs as well as real help text/images for helping users complete profile.

**Comment by Vensberg** [comment]
Do you mean screen shots of how to update the profile? Is this dependent on the app or will screenshots on the ORCID interface do?

**Comment by jrmerz** [comment]
checklist reference: https://docs.google.com/document/d/1S7i8-xBC6h2-am7ibhGCjNPJbMFX0sG3drYbLgtC8ns/edit?usp=sharing
