### ISSUE TITLE
Kimmy signoff on UI

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/orcid-app#25]
@wrenaria Just close this when the app UI gets your approval.

**Comment by jrmerz** [comment]
@Vensberg let me know when you have final text for the crossref help page.  Once I implement the final crossref help page into the app I will have kimmy give the final sign-off on the design implementation for the entire app.

**Comment by Vensberg** [comment]
I just editing finished the text. There are two things needed for sign off. 1) The website uses @jrmerz screenshot of a CrossRef communication about his paper. I want to make sure that is OK with him. 2) I gave people till 10/30 to comment on the text, so let's leave the official sign off until then.

**Comment by Vensberg** [comment]
Text is here: https://docs.google.com/document/d/1lejIeBCgawV9GUREaHXBY2FqMQL53PxCgf9wKRRXJVI/edit

**Comment by jrmerz** [comment]
Approved.

**Comment by Vensberg** [comment]
There may still be comments on 10/30.
