### ISSUE TITLE
Production ringgold Ids

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/orcid-app#28]
The app is currently using fake ringgold id's for CoE and EEI.  According to quinns work CoE is 140245, correct?  I was unable to find what ID to assign EEI.

**Comment by Vensberg** [comment]
CoE is 140245, EEI is 522604, for reference: https://docs.google.com/spreadsheets/d/16V33mrRFxQawGaaGePlUHcYCIjBHbWpmk84SVw1iquE/edit#gid=1355834546

**Comment by jrmerz** [comment]
thanks!
