### ISSUE TITLE
App does not detect deleted employment record

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/orcid-app#32]
**Describe the bug**
When I log into CAS, I get employment present, but I have already deleted it from my sandbox ORCID.

**To Reproduce**
1. Go to 'http://dev.orcid.library.ucdavis.edu'
2. Log in with CAS
3. Employment record is there, but I have already deleted it from the sandbox. Profile is at 20%.

**Expected behavior**
Since I already deleted employment, I expect 0 %

**Screenshots**
<img width="960" alt="employment_present" src="https://user-images.githubusercontent.com/26015534/47668227-1c6ebf80-db65-11e8-8512-1fc1fb0ab9d8.png">
<img width="960" alt="employment_deleted" src="https://user-images.githubusercontent.com/26015534/47668235-20024680-db65-11e8-9f58-4487458f958b.png">

**Device (please complete the following information):**
Windows 10 Pro
Microsoft Edge 40.15063.674.0
Microsoft EdgeHTML 15.15063

**Additional context**

**Comment by Vensberg** [comment]
I think it took a bit of time to update between the orcid sandbox and app sandbox. After ~ 30 min, I refreshed, and I got the expected no-employment record.

**Comment by jrmerz** [comment]
Had you clicked the 'Reload iD Score' button?

**Comment by Vensberg** [comment]
No, I think I started from scratch (i.e. I did not have the filled out profile scored).

**Comment by jrmerz** [comment]
@Vensberg so close issue?

**Comment by Vensberg** [comment]
Yes
