### ISSUE TITLE
Failed to update employment

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/orcid-app#33]
**Describe the bug**
This is building on my previous issue of deleting employment. The app is showing employment after I deleted it. When I edit it in the app, I get an error "failed to update employment"

**To Reproduce**
1. Go to 'http://dev.orcid.library.ucdavis.edu'
2. Click on Edit employment (the blue pencil)
3. In the new window, I made sure my employment title is **un**clicked
4. I get  "failed to update employment"

**Expected behavior**
I am not sure since the employment was not deleted in the first place

**Screenshots**
<img width="960" alt="failed_to_update_employment" src="https://user-images.githubusercontent.com/26015534/47668813-a703ee80-db66-11e8-8720-a4bc20ae183a.png">

**Device (please complete the following information):**
 - OS: [e.g. iOS, Windows, Android]

**Additional context**

**Comment by jrmerz** [comment]
Lets meet up to chat about this one when you have a chance

**Comment by Vensberg** [comment]
I will be available at 3 PM, but I think that this is actually OK. This issue builds on https://github.com/ucd-library/orcid-app/issues/32 and since I had truly deleted the employment, it makes sense that the app couldn't do anything more.

**Comment by jrmerz** [comment]
@Vensberg bug fix pushed to dev and production environments.  Can you test?  If it looks good, go ahead a close.

**Comment by Vensberg** [comment]
It's fixed.
